error handling Dune

diff --git a/.github/workflows/lido-oracle-report-upload.yml b/.github/workflows/lido-oracle-report-upload.yml
--- a/.github/workflows/lido-oracle-report-upload.yml
+++ b/.github/workflows/lido-oracle-report-upload.yml
@@ -52,4 +52,13 @@ jobs:
 
       - name: Upload Oracle Report to Dune Analytics
         shell: bash -l {0}
-        run: python scripts/upload_to_dune.py --type oracle 
+        run: |
+          # Run the upload script and capture its output
+          output=$(python scripts/upload_to_dune.py --type oracle --table-name dune.asot.dataset_lido_oracle_report_data 2>&1)
+          echo "$output"
+          
+          # Check if the output contains error messages and fail the workflow if it does
+          if echo "$output" | grep -q "Error"; then
+            echo "::error::Upload to Dune Analytics failed"
+            exit 1
+          fi 
diff --git a/.github/workflows/lido-withdrawal-times-upload.yml b/.github/workflows/lido-withdrawal-times-upload.yml
--- a/.github/workflows/lido-withdrawal-times-upload.yml
+++ b/.github/workflows/lido-withdrawal-times-upload.yml
@@ -46,4 +46,13 @@ jobs:
       
       - name: Upload Withdrawal Times to Dune Analytics
         shell: bash -l {0}
-        run: python scripts/upload_to_dune.py --type withdrawal 
+        run: |
+          # Run the upload script and capture its output
+          output=$(python scripts/upload_to_dune.py --type withdrawal --table-name dune.asot.dataset_historical_steth_withdrawal_times_by_amount 2>&1)
+          echo "$output"
+          
+          # Check if the output contains error messages and fail the workflow if it does
+          if echo "$output" | grep -q "Error"; then
+            echo "::error::Upload to Dune Analytics failed"
+            exit 1
+          fi 
